"""add b2b fields

Revision ID: 1234567890ab
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1234567890ab'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_type', sa.String(length=50), nullable=True, server_default='sale'))
    op.add_column('tasks', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'amount')
    op.drop_column('tasks', 'company_name')
    op.drop_column('tasks', 'task_type')
    # ### end Alembic commands ###
